language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"
# command to install dependencies
install: "pip install -r aguante/requirements.txt"
# command to run tests
script: cd aguante; python manage.py test
