# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0008_auto_20150824_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='nombre_youtube',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='youtube_url',
        ),
    ]
